### PR TITLE
Fixed the comiling error when installing with melpa caused by 1.2.6

### PR DESCRIPTION
**Pull request by alphatan**
* Comments

    **Only tested in manual installation**

    **Please DO a test with melpa before releasing**

    Thanks

* Changes

    1. Fixed the comiling error when installing with melpa, surround the `defcustom-list` with `(eval-and-compile ...)` block ;
    1. update the version number to 1.2.7 ;

* Links
    - Problem PR: #74
    - Original Compling Problem: #51

### CODE REVIEW

**Comment by skuro** [comment]
merged as f416fe7

**Comment by skuro** [comment]
I just merged all the code to `master`, which should update MELPA unstable. My local compilation testing suggest we should be bug free, as soon as MELPA processes the new commit I'll test again and release to stable if everything looks good.

**Comment by skuro** [comment]
MELPA unstable just released the new snapshot, which works awesomely so I also issued a stable release. Thanks for you contribution!

**Comment by alphatan** [comment]
Hurray~! :tada::tada::tada:

**Pull request closed without merging**
