### PR TITLE
Indentation improvements

### PR DESCRIPTION
**Pull request by joodie**

### CODE REVIEW

**Comment by joodie** [comment]
Finally got around to get the tests working. This implements and tests all the examples in on the [new activity diagram page](http://plantuml.com/activity-diagram-beta).

Also introduces a customizable indent width for plantuml-mode (defaults to 8 chars for backwards compatibility reasons).

**Comment by joodie** [comment]
How's this? As far as I can tell, there's no need to use readlink/realpath at all.

**Comment by skuro** [comment]
LGTM, thanks!

**Comment by fkgruber** [comment]
> Finally got around to get the tests working. This implements and tests all the examples in on the [new activity diagram page](http://plantuml.com/activity-diagram-beta).
> 
> Also introduces a customizable indent width for plantuml-mode (defaults to 8 chars for backwards compatibility reasons).

how do you activate the indentation?
I tried one of the examples and nothing gets indented:
```
@startuml
start
if (condition A) then (yes)
:Text 1;
elseif (condition B) then (yes)
:Text 2;
stop
elseif (condition C) then (yes)
:Text 3;
elseif (condition D) then (yes)
:Text 4;
else (nothing)
:Text else;
endif
stop
@enduml

```

I'm using  plantuml from melpa
Status: Installed in ‘plantuml-mode-1.4.1/’ (unsigned).
    Version: 1.4.1
     Commit: 5889166b6cfe94a37532ea27fc8de13be2ebfd02
    Summary: Major mode for PlantUML
   Requires: dash-2.0.0, emacs-25.0
   Keywords: uml plantuml ascii 
Other versions: 1.4.1 (melpa).

**Comment by joodie** [comment]
@fkgruber when you've got that code in a buffer, ensure you've got `plantuml-mode` enabled.

To indent the whole buffer, select everything using `mark-whole-buffer` (`C-x h`) , then call `indent-region`.

Key bindings for per line indentation can be configured in many ways, but calling `indent-according-to-mode` should indent the current line (try on the `:Text 1;` line).

**Comment by fkgruber** [comment]
tried it nothing happens.
I created a file that has that code I made sure plantuml-mode is active but I can't get it to indent.

THis are the modes active on that windows. Perhaps there is a conflict somewhere?
```
Enabled minor modes: Async-Bytecomp-Package Auto-Composition
Auto-Compression Auto-Dim-Other-Buffers Auto-Encryption Blink-Cursor
Conda-Env-Autoactivate Delete-Selection Diff-Auto-Refine Display-Time
Electric-Indent Electric-Pair File-Name-Shadow Font-Lock Global-Eldoc
Global-Font-Lock Global-Hl-Line Global-Undo-Tree Ido-Everywhere Ivy
Line-Number Menu-Bar Mouse-Wheel Org-Roam Org-Roam-Bibtex
Org-Roam-Server Org-Wild-Notifier Override-Global Pdf-Occur-Global
Recentf Shackle Shell-Dirtrack Show-Paren Straight-Package-Neutering
Straight-Use-Package Tool-Bar Tooltip Transient-Mark Undo-Tree Winner

(Information about these minor modes follows the major mode info.)

plantuml mode defined in ‘plantuml-mode.el’:
Major mode for plantuml.

```

**Comment by fkgruber** [comment]
I tried running emacs without configuration (-q option) and still does not work.
Here are the active modes:

```
Enabled minor modes: Auto-Composition Auto-Compression Auto-Encryption
Blink-Cursor Delete-Selection Diff-Auto-Refine Electric-Indent
File-Name-Shadow Font-Lock Global-Eldoc Global-Font-Lock Line-Number
Menu-Bar Mouse-Wheel Shell-Dirtrack Show-Paren Tool-Bar Tooltip
Transient-Mark

(Information about these minor modes follows the major mode info.)

plantuml mode defined in ‘plantuml-mode.el’:
Major mode for plantuml.

Shortcuts             Command Name
M-x plantuml-complete-symbol      ‘plantuml-complete-symbol’

In addition to any hooks its parent mode ‘prog-mode’ might have run,
this mode runs the hook ‘plantuml-mode-hook’, as the final or penultimate step
during initialization.

```

**Pull request merged**
