### PR TITLE
Support plantuml as executable in PATH

### PR DESCRIPTION
**Pull request by lucafavatella**
- [ ] Test JAR
- [x] Test wrapper binary
- [ ] Review by Emacs Lisp expert

---

Please refer to commit message for details.

I use OS X Homebrew so I use the plantuml wrapper binary in the PATH.

### CODE REVIEW

**Comment by lucafavatella** [comment]
(I see that org babel export has [independent code for calling plantuml](http://orgmode.org/cgit.cgi/org-mode.git/tree/lisp/ob-plantuml.el?id=release_8.3.4#n59), and it requires similar change. Out of scope for this pull request though.)

**Comment by skuro** [comment]
This PR has become a bit outdated after the merge with `plantuml-mode` and further changes. Care to update it?

**Comment by lucafavatella** [comment]
@skuro No, I do not plan to update this.

**Comment by skuro** [comment]
Closing as way too outdated compared to the current codebase

**Comment by lucafavatella** [comment]
It seems [recent merged PR](https://github.com/skuro/plantuml-mode/pull/102/files#diff-04c6e90faac2675aa89e2176d2eec7d8R100) implemented analogous functionality. So no need to update this PR.

**Pull request closed without merging**
