### PR TITLE
Run plantuml as executable not as jar

### PR DESCRIPTION
**Pull request by FlexW**
Adds functionality to plantuml-mode to run plantuml as a normal executable.
For example NixOs provides a package with a binary plantuml. It would be nice to use this binary directly.

### CODE REVIEW

**Comment by skuro** [comment]
I just pushed [`feature/run-modes`](https://github.com/skuro/plantuml-mode/tree/feature/run-modes) which adds support for rendering using the PlantUML server, I think the code structure there makes it easy for you to add support for executable-based rendering in a clean fashion. Thoughts?

**Comment by FlexW** [comment]
I just had a quick look on it but it looked good. If I have a little spare time, I will try to add support for the executable.

**Comment by skuro** [comment]
The `feature/run-modes` branch was merged into `develop` today, so I've introduced merge conflicts with your branch. Are you still planning to work on this feature?

**Comment by FlexW** [comment]
Yes, I will work on this feature. We may close this pull request? I will then make a new pull request with adding the support for executables to the run-modes.

**Comment by skuro** [comment]
Sounds good to me, thanks for your efforts in advance :-)
Closing this one and looking forward to the next one

**Pull request closed without merging**
