### PR TITLE
Replaced shell-command with call-process. this fixes a couple issues:…

### PR DESCRIPTION
**Pull request by abcdec**
… (1) when the mode is first loaded and plantuml-init is executed, Emacs window is split into two, which is not necessary. (2) under cygwin emacs and windows native Java combination, shell-quote-argument is cauisng file path format change and making Java unable to load jar file.  file-exists-p is also skipped if cygwin emacs is running.

### CODE REVIEW

**Comment by skuro** [comment]
Tested with Cygwin Emacs in a Win10 VM. It seems to me that these changes alone are not enough for the system to properly work there. Init doesn't seem to work and preview is broken. Is there any chance that your other PR should be merged before this one?

**Comment by skuro** [comment]
Some more details: in `ielm`, here's what happens:

```
ELISP> (call-process "java" nil t nil "-jar" plantuml-jar-path "-language")
1 (#o1, #x1, ?\C-a)
ELISP> Error: Unable to access jarfile /cygdrive/c/Users/IEUser/plantuml/plantuml.jar^M
```

Not sure if that trailing `^M` is a hint to something here..

**Comment by abcdec** [comment]
If you are using cygwin but java is Windows native, I think the path you will set for jar file must be Java Windows path format, which is like "C:/Users/IEUser/plantuml/plantuml.jar".  This is the part causing annoying issue with cygwin - java combo.  ^M is just an output from Java including CR-LF and CR appears to be ^M.  You can ignore.  The issue is path format for the jar file.

**Comment by abcdec** [comment]
Resubmitted against develop branch. #41.  Close this one.

**Pull request closed without merging**
