### PR TITLE
Enable to use PlantUML Server.

### PR DESCRIPTION
**Pull request by yewton**
related  #27 

What do you think about this approach? 🤔

### CODE REVIEW

**Comment by skuro** [comment]
Hi @yewton, first of all thanks for the PR! The approach is interesting, albeit I would actually prefer not to add python in the mix (read: the compression should be implemented in elisp). The reason for that is that multi-OS support is already quite brittle, and having one extra component to the mix would complicate the picture quite a lot. What do you think?

On the other hand, seems like the code [broke the build](https://travis-ci.org/skuro/plantuml-mode/builds/331130516?utm_source=github_status&utm_medium=notification), so something fishy is going on with the preview.

**Comment by yewton** [comment]
I'm sorry for annoying commits/builds bomb 🙇 
Now I and also Travis settled down.

> having one extra component to the mix would complicate the picture quite a lot

I agree with you.

However, implementing (PlantUML Text Encoding)[http://plantuml.com/pte] in pure elisp will be quit hard.

* Emacs does not support Deflate. 
    * zlib is used but for decompressing only ( https://git.savannah.gnu.org/cgit/emacs.git/tree/src/decompress.c?h=emacs-25.3 )
* Implementing Deflate means porting https://github.com/madler/zlib/blob/master/deflate.c to elisp. Seems so hard 😓 

I have several approaches to support PlantUML Server without additional external program:

1. Emulate form request to PlantUML Server OSS and follow the redirect response from the server
    * We have to drop [Public PlantUML Server](http://www.plantuml.com/plantuml/) support because it does not redirect but compress the text within JavaScript
    * We have to introduce `curl` dependency ( via [request.el](https://github.com/tkf/emacs-request) ) because `url-retrieve` cannot handle form request and redirection properly ( It seems possible without curl, but it doesn't work (without hack). See bottom snippet. )
1. GET with `?text=<URL encoded plain diagram text>` will return a HTML page including the URL for the image, so parse or regex match it and retrieve the image
    * This is undocumented behavior
    * HTML structure may change in the future
1. Implement an alternative PlantUML Server in JVM language that allows plain text
    * It's not so difficult, maybe. Just a thin wrapper of plantuml
    * Requires JRE. That's not a problem, is it?
    * Unofficial solution ☹️ 
1. Make Emacs support deflate
1. Make PlantUML Server support plain text

Which approach ( or another ) should I take? 🤔 


### P.S. PlantUML Server with `url-retrieve` test 

```elisp
(let ((url-request-method "POST")
      (url-request-extra-headers
       '(("Content-Type" . "application/x-www-form-urlencoded")))
      (url-request-data "text=test"))
  (url-retrieve "http://localhost:8080/form" (lambda (&rest _ignore) (switch-to-buffer (current-buffer)))))
;; CALLBACK is never called...
;; Possible workaround: https://stackoverflow.com/a/40564493/2142831
```

**Comment by yewton** [comment]
I have made [a feature request to accept plain text](https://github.com/plantuml/plantuml-server/issues/67) and the request have been accepted!
When it has been released, I will rework this PR.

**Comment by skuro** [comment]
Hey! Sorry for the delay, I needed some time to consider your approach and look around for potential alternatives. I actually think that a better solution would be to use good old `gzip` instead of python to work with compression. On a Windows machine that would require Cygwin, but:
a) part of our Windows user base is actually using Cygwin-installed Emacs
b) the others won't have much harder time installing Cygwin+gzip instead of just Python
I would still like it more than shipping `plantuml-mode` with the python script.

**Comment by yewton** [comment]
Thanks for your reply!
I'll close this PR for now, thanks.

**Pull request closed without merging**
